theme = "vim_dark_high_contrast"

[editor]
line-number = "absolute"
mouse = false
auto-format = true
auto-completion = true
insert-final-newline = true
gutters = ["spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-signature-help-docs = true
snippets = true

[editor.smart-tab]
enable = true
